.TH noblenote 1 "2015-03-24"
.PP
.SH NAME
nobleNote \- An Qt program for taking notes
.PP
.SH SYNOPSIS
.B noblenote
.PP
.SH DESCRIPTION
nobleNote is a program to organize and create notes. It has an icon
in the system tray and supports drag and drop. The note-editor supports
different fonts, font sizes and colors as well as background colors.
You can also import notes from other programs like gnote and tomboy.
The notes are saved in the html format.
.PP
.SH AUTHORS
Fabian Deuchler <Taiko000@gmail.com>, Christian Metscher <hakaishi@web.de>
